[package]
name = "noumenon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.8.4"
ironworks = {version = "0.3.1", features = ["ffxiv", "sqpack"]}