[package]
name = "aetherment"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aetherment_core"
crate-type = ["dylib"]

# i'm too dumb to figure out how to get the device on rust side
# [dependencies.windows]
# version = "0.37.0"
# features = [
# 	"Win32_Graphics_Direct3D11",
# 	"Win32_Foundation",
# 	"Win32_Graphics_Direct3D",
# 	"Win32_Graphics_Dxgi",
# 	"Win32_Graphics_Dxgi_Common",
# ]

[dependencies]
lazy_static = "1.4.0"
image = "0.24.2"
reqwest = {version = "0.11.10", features = ["blocking", "json"]}
noumenon = {path = "../noumenon"}